version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      dev-deps:
        patterns: ["@playwright*", "serve"]
      prod-deps:
        patterns: ["puppeteer", "gif-encoder-2", "pngjs", "@mermaid-js*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
